/**
 * Alert service (read side).
 *
 * Responsibility: List a site's alerts (paginated), authorized via project
 * membership. Alerts are generated by the evaluation pipeline; this service only
 * reads and maps them to DTOs.
 */
import type { Alert } from '@prisma/client';

import { Capability } from '@/lib/auth/rbac';
import { requireCapabilityOnSite } from '@/lib/auth/authorization';
import { analyticsRepository } from '@/lib/repositories/analyticsRepository';
import type { AuthUser } from '@/types';
import type { PaginationQuery } from '@/schemas/common';

function toDto(a: Alert) {
  return {
    id: a.id,
    siteId: a.siteId,
    category: a.category,
    severity: a.severity,
    title: a.title,
    reason: a.reason,
    recommendation: a.recommendation,
    confidence: a.confidence,
    resolvedAt: a.resolvedAt ? a.resolvedAt.toISOString() : null,
    createdAt: a.createdAt.toISOString(),
  };
}

export const alertService = {
  async listBySite(user: AuthUser, siteId: string, pagination: PaginationQuery) {
    await requireCapabilityOnSite(user.id, siteId, Capability.VIEW_ALERTS);
    const skip = (pagination.page - 1) * pagination.pageSize;
    const { items, total } = await analyticsRepository.listAlerts(siteId, {
      skip,
      take: pagination.pageSize,
    });
    return { items: items.map(toDto), total };
  },
};
